# golangci-linter configuration
# See https://github.com/golangci/golangci-lint#config-file for reference.

run:
  # TODO(skeleton): Configure build tags, if any
  build-tags: {}
  skip-dirs:
    - protogen/

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - log                         # prefer go.uber.org/zap
      - github.com/gogo/protobuf    # prefer github.com/golang/protobuf
      - github.com/pkg/errors       # prefer golang.org/x/xerrors
      - github.com/sirupsen/logrus  # prefer go.uber.org/zap
      - golang.org/x/xerrors        # prefer fmt.Errorf with error wrapping
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    # report about shadowed variables
    check-shadowing: false
  lll:
    line-length: 140
    tab-width: 4
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gomnd
    - interfacer
    - wsl

