language: go
go:
- "1.10"
addons:
  postgresql: '9.5'
services:
- postgres
- docker
sudo: true
env:
  - LIBRDKAFKA_VERSION=v0.11.5
cache:
  directories:
  - "$HOME/.cache/librdkafka"
before_install:
- sudo /bin/bash ./travis-install-librkafka.sh
install:
- make setup-ci
script:
- make test
after_success:
- "$HOME/gopath/bin/goveralls -coverprofile ./_build/test-coverage-all.out -service=travis-ci"
- "./push_to_docker.sh"
