---
gracefulShutdownTimeout: 30
apns:
  concurrentWorkers: 100
  logStatsInterval: 10000
  # games:
  #   game: /certs/cert.pem
gcm:
  pingInterval: 30
  pingTimeout: 10
  maxPendingMessages: 100
  logStatsInterval: 10000
  # games:
  #   game:
  #     apiKey: game-api-key
  #     senderID: "1233456789"
queue:
  topics:
    - "^push-[^-_]+_(apns|gcm)[_-](single|massive)"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
  channelSize: 100
feedback:
  reporters:
    - kafka
  kafka:
    topics: "push-test_apns-feedbacks"
    brokers: "localhost:9941"
  cache:
    requestTimeout: 86400000
    cleaningInterval: 300000
stats:
  reporters:
    - statsd
  statsd:
    host: "localhost:8125"
    prefix: "push"
    flushIntervalMs: 5000
invalidToken:
  handlers:
    - pg
  pg:
    table: "test_apns"
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
    connectionTimeout: 100
