---
gracefulShutdownTimeout: 30
apns:
  concurrentWorkers: 300
  connectionPoolSize: 1
  logStatsInterval: 10000
  apps: "game"
  certs:
    game:
      authKeyPath: /certs/authkey.p8
      keyID: "ABC123DEFG"
      teamID: "ABC123DEFG"
      topic: "com.game.test"
gcm:
  pingInterval: 30
  pingTimeout: 10
  maxPendingMessages: 100
  logStatsInterval: 10000
  apps: mygame, anothergame
  certs:
    game:
      apiKey: game-api-key
      senderID: "1233456789"
  firebaseCredentials:
    mygame: "{\n  \"type\": \"service_account\",\n  \"project_id\": \"gilded-gardens-63066737\",\n  \"private_key_id\": \"4e769e89b6a6144987575b9dcd5f75cb8ef0c0de\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtHU9A9knM7el2\\n3466F2FhgxuUebDEMDd00oh920CkR3gkUiHzLNbXcKhrCjY2zlJ8kc6bHSy4IqkA\\nWgGYxCCGlLFAMoKPGPcEmDUenQhrFiAVn7f5qW0PbKOWqNw36GXACjoxB9dQGZAQ\\nRkS0yrTJ3wSA41PfR50h9n92BWJqlweXMqHzFJxj9eefhUPCQKg1TYbpE9fYhkbP\\nX6uavAvIYnzEwuA6J58lJm/iWlkNfSKeHI0jt/kNuR1czB4NZc4zMTBOrD0NZ0A6\\nZkMekfNOETc483HKCVFXe/vH/5hcIwna3OqAZxI6MToBgrJfPXTMkCq5S99kq44B\\nTEhQ+ED7AgMBAAECggEAFw4IOAaU3Y3xwbsULwReG7ZyPdvXBsnFGPHQ67H/ceFy\\nxqOJkfEuy5JdW6QIhFQF+EES2uWPxxYWm81g2Q+FpWa4FGylppkUjLAYovMW4+wW\\nacrTnZRKyfsV7kKe0XNJ2cGC7nS04B4HaaNyEwHMAfaJiwC7csj+zD8fyn/9E2TB\\nswGPTqE+0Kp2ML8mt83NcGoVRKrGzJaVdLMw3rUutWmb52zciiR2aW1OefHtxDFm\\n5MVP6EPP3yiLemRQQLEZ9bOMQSQLfjZNo3W5uv9y4OLG5XaXM1gH0woGCCNrngNZ\\nNZjengserQ0RnTsXK8r68s6rmhYTmu2XwmVMR0ccAQKBgQDUIQIgyPjFzsvbyNCl\\nJ5W9IN+QxM+3Npf8B4+VII3HP6MZ94ME0HNfZ9BWl4+loZVYmtanHrnEATErooLB\\n1yUnfEqDipB7Vtw/5phsUMl+Aam/CVPizEh7lqztRYtputY0QPgu9apjfQB15i3U\\nJQ457kuOpAxUXReWmL7fnF8EQQKBgQDQ6ranpBvpxIaH33coX2drt/4aUGDjLHMK\\n3DVKv3VxCn+F9+7Jm+OhpjtaE6NJ4qlITniuAomVZtuizNRtqeTTkTIsgt4kqv4Z\\nnhapfugyphuvUjCrF5ZFWurywgAoBJYRLHypCWVBY3IJfq8T/oVh4nG1ZxdAYeHK\\nW0OIt8jGOwKBgQCqntYgWqXGLNxJro8rl9hX5B4OSk8sdUvv2oEBmMqQzb25gByw\\n/Z0eytiHHabbuUjvmLM4fn06ix7qku8LTKpExTMF9Kjbm/TRrP9CeARpRpsq3izL\\nyjYuufXjbsGAzFfIdc1psA1ZskxxiC+qaBe2PtYlKAwGu03iwn8cSqEeQQKBgFLC\\nyHz8q/odWlX1FpUtxiCMEOOHt/oGn8RLm+jyk6mmSQJfR38ifDiLS7PRV7xrSDhW\\nrcPxSWOgDZ4emoCe7wFI4aF0bmAERQkM8VlP5tg5qXn4i0Mb4vGypKRqaflwZ6qB\\n/xhPmoceyAwu3ViEWX5/YCBGqJVesT2ijcxZUfYFAoGBAMMThE7jeml3DNTv1Qyl\\nryp4C6UrkGhNwjx/d53782BC3o1f2bJUSG11OftI5cko5hE4KD5W0nIyjLmShalr\\n/ldCgK+1IwrviY4dJdZstT76Vdz2XqYywFaXWWNNU6CnK/FRI+YUr4xNza11LzjO\\nJfGoRe5IErrgb/Dmz+SbW8Ad\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"firebase-adminsdk-909vs@gilded-gardens-63066737.iam.gserviceaccount.com\",\n  \"client_id\": \"103930365174654016718\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-909vs%40gilded-gardens-63066737.iam.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}"
    anothergame: "{\n  \"type\": \"service_account\",\n  \"project_id\": \"gilded-gardens-63066737\",\n  \"private_key_id\": \"4e769e89b6a6144987575b9dcd5f75cb8ef0c0de\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtHU9A9knM7el2\\n3466F2FhgxuUebDEMDd00oh920CkR3gkUiHzLNbXcKhrCjY2zlJ8kc6bHSy4IqkA\\nWgGYxCCGlLFAMoKPGPcEmDUenQhrFiAVn7f5qW0PbKOWqNw36GXACjoxB9dQGZAQ\\nRkS0yrTJ3wSA41PfR50h9n92BWJqlweXMqHzFJxj9eefhUPCQKg1TYbpE9fYhkbP\\nX6uavAvIYnzEwuA6J58lJm/iWlkNfSKeHI0jt/kNuR1czB4NZc4zMTBOrD0NZ0A6\\nZkMekfNOETc483HKCVFXe/vH/5hcIwna3OqAZxI6MToBgrJfPXTMkCq5S99kq44B\\nTEhQ+ED7AgMBAAECggEAFw4IOAaU3Y3xwbsULwReG7ZyPdvXBsnFGPHQ67H/ceFy\\nxqOJkfEuy5JdW6QIhFQF+EES2uWPxxYWm81g2Q+FpWa4FGylppkUjLAYovMW4+wW\\nacrTnZRKyfsV7kKe0XNJ2cGC7nS04B4HaaNyEwHMAfaJiwC7csj+zD8fyn/9E2TB\\nswGPTqE+0Kp2ML8mt83NcGoVRKrGzJaVdLMw3rUutWmb52zciiR2aW1OefHtxDFm\\n5MVP6EPP3yiLemRQQLEZ9bOMQSQLfjZNo3W5uv9y4OLG5XaXM1gH0woGCCNrngNZ\\nNZjengserQ0RnTsXK8r68s6rmhYTmu2XwmVMR0ccAQKBgQDUIQIgyPjFzsvbyNCl\\nJ5W9IN+QxM+3Npf8B4+VII3HP6MZ94ME0HNfZ9BWl4+loZVYmtanHrnEATErooLB\\n1yUnfEqDipB7Vtw/5phsUMl+Aam/CVPizEh7lqztRYtputY0QPgu9apjfQB15i3U\\nJQ457kuOpAxUXReWmL7fnF8EQQKBgQDQ6ranpBvpxIaH33coX2drt/4aUGDjLHMK\\n3DVKv3VxCn+F9+7Jm+OhpjtaE6NJ4qlITniuAomVZtuizNRtqeTTkTIsgt4kqv4Z\\nnhapfugyphuvUjCrF5ZFWurywgAoBJYRLHypCWVBY3IJfq8T/oVh4nG1ZxdAYeHK\\nW0OIt8jGOwKBgQCqntYgWqXGLNxJro8rl9hX5B4OSk8sdUvv2oEBmMqQzb25gByw\\n/Z0eytiHHabbuUjvmLM4fn06ix7qku8LTKpExTMF9Kjbm/TRrP9CeARpRpsq3izL\\nyjYuufXjbsGAzFfIdc1psA1ZskxxiC+qaBe2PtYlKAwGu03iwn8cSqEeQQKBgFLC\\nyHz8q/odWlX1FpUtxiCMEOOHt/oGn8RLm+jyk6mmSQJfR38ifDiLS7PRV7xrSDhW\\nrcPxSWOgDZ4emoCe7wFI4aF0bmAERQkM8VlP5tg5qXn4i0Mb4vGypKRqaflwZ6qB\\n/xhPmoceyAwu3ViEWX5/YCBGqJVesT2ijcxZUfYFAoGBAMMThE7jeml3DNTv1Qyl\\nryp4C6UrkGhNwjx/d53782BC3o1f2bJUSG11OftI5cko5hE4KD5W0nIyjLmShalr\\n/ldCgK+1IwrviY4dJdZstT76Vdz2XqYywFaXWWNNU6CnK/FRI+YUr4xNza11LzjO\\nJfGoRe5IErrgb/Dmz+SbW8Ad\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"firebase-adminsdk-909vs@gilded-gardens-63066737.iam.gserviceaccount.com\",\n  \"client_id\": \"103930365174654016718\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-909vs%40gilded-gardens-63066737.iam.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}"


queue:
  topics:
    - "^push-[^-_]+_(apns|gcm)[_-](single|massive)"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
  channelSize: 100
feedback:
  reporters:
    - kafka
  kafka:
    topics: "push-test_apns-feedbacks"
    brokers: "localhost:9941"
  cache:
    requestTimeout: 1800000
    cleaningInterval: 300000
stats:
  reporters:
    - statsd
  flush:
    s: 5
  statsd:
    host: "localhost:8125"
    prefix: "push"
    buflen: 1
invalidToken:
  pg:
    table: "test_apns"
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
    connectionTimeout: 100
feedbackListeners:
  queue:
      topics:
        - "^push-[^-_]+-(apns|gcm)-feedbacks"
      brokers: "localhost:9941"
      group: testGroup
      sessionTimeout: 6000
      fetch.min.bytes: 1
      fetch.wait.max.ms: 100
      offsetResetStrategy: latest
      handleAllMessagesBeforeExiting: true
  broker:
    invalidTokenChan:
      size: 999
  invalidToken:
    flush:
      time:
        ms: 2000
    buffer:
      size: 99
    pg:
      host: localhost
      port: 8585
      user: pusher_user
      pass: ""
      poolSize: 20
      maxRetries: 3
      database: push
      connectionTimeout: 100
