---
gracefulShutdownTimeout: 10
apns:
  concurrentWorkers: 100
  logStatsInterval: 750
  apps: "game"
  certs:
    game: ../tls/self_signed_cert.pem
gcm:
  pingInterval: 30
  pingTimeout: 10
  maxPendingMessages: 3
  logStatsInterval: 750
  apps: "game"
  certs:
    game:
      apiKey: game-api-key
      senderID: "1233456789"
queue:
  topics:
    - "^push-[^-_]+_(apns|gcm)[_-](single|massive)"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
feedback:
  reporters:
    - kafka
  kafka:
    topics: "com.games.test.feedbacks"
    brokers: "localhost:9941"
  cache:
    requestTimeout: 100
    cleaningInterval: 20
stats:
  reporters:
    - statsd
  statsd:
    host: "localhost:40001"
    prefix: "push"
    flushIntervalMs: 5000
invalidToken:
  handlers:
    - pg
  pg:
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
    connectionTimeout: 100
